#!/bin/bash

###############################################################################
#
# ./hipchat_room_message
#
# A script for sending a system message to a room.
# 
# Docs: http://github.com/hipchat/hipchat-cli
# 
# Usage:
#   cat message.txt | ./hipchat_room_message -t <token> -r 1234 -f "System"
#   echo -e "New\nline" | ./hipchat_room_message -t <token> -r 1234 -f "System"
#
###############################################################################

# exit on failure
set -e

usage() {
  cat << EOF
Usage: $0 -t <token> -r <room id> -f <from name>

This script will read from stdin and send the contents to the given room as
a system message.

OPTIONS:
   -h  Show this message
   -t  API token
   -r  Room ID
   -f  From name
EOF
}

TOKEN=
ROOM_ID=
FROM=
MESSAGE=
while getopts “ht:r:f:” OPTION; do
  case $OPTION in
    h) usage; exit 1;;
    t) TOKEN=$OPTARG;;
    r) ROOM_ID=$OPTARG;;
    f) FROM=$OPTARG;;
    [?]) usage; exit;;
  esac
done

# check for required args
if [[ -z $TOKEN ]] || [[ -z $ROOM_ID ]] || [[ -z $FROM ]]; then
  usage
  exit 1
fi

# read stdin
INPUT=$(cat)

# replace newlines with XHTML <br />
INPUT=$(echo -n "${INPUT}" | sed "s/$/<br \/>/")

# do the curl
curl -sS \
  -H "Authorization: HipChat $TOKEN" \
  -d "room_id=$ROOM_ID&from=$FROM&message=$INPUT" \
  http://api.hipchat.com/v1/rooms/message
